### ISSUE TITLE
Use native promises

### ISSUE THREAD

**Issue by niftylettuce** [aheckmann/mquery#93]

**Comment by aheckmann** [comment]
I would be in favor of native promises only when we drop support for all
versions of Node < 8.0.0. Some apps use domains, and before Node 8, native
Promises didn't support them which leads to hard to debug problems.
Bluebird works better.

**Comment by vkarpov15** [comment]
We can close this for now, Automattic/mongoose#5945 makes it so that mongoose configures mquery to use native promises by default, so this isn't a necessary change as far as mongoose is concerned.

FWIW I haven't seen any apps that use domains, in my experience domains are badly broken. Have you seen people using domains @aheckmann ?

**Comment by aheckmann** [comment]
Kraken and restify (PayPal and Netflix)
